#!/usr/bin/env python3
"""Evaluate the detector on the 20 test photos against the reference labels.

The script runs the compiled C program on every text image of IMG_300/ and
compares what it reports with IMG_300/ground_truth.csv. It writes:

    results/detections.csv   one row per ball (labelled or detected)
    results/masks.csv        per ball: mask coverage, bounding box, corrected output
    results/brightness.csv   detections when the photos are darkened or brightened
    results/summary.json     every aggregate number
    results/results.md       the tables shown in the README

and refreshes the block between the 'results' markers of README.md.

    python scripts/evaluate.py            # recompute and write everything
    python scripts/evaluate.py --check    # recompute and fail if a committed file differs

Only the standard library is used; nothing here is random.
"""

import argparse
import csv
import io
import json
import math
import statistics
import sys

from common import (COLOURS, PHOTO_DIR, RESULTS_DIR, ROOT, WORK_DIR, find_binary, image_names,
                    load_ground_truth, mask_bounding_box, read_pgm, run_detector)

README = ROOT / "README.md"
README_START = "<!-- results:start (generated by scripts/evaluate.py) -->"
README_END = "<!-- results:end -->"

# Brightness sweep: every sample is multiplied by gain / 100 and clipped to 255.
BRIGHTNESS_GAINS = (50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150)


# ---------------------------------------------------------------------------
# Geometry
# ---------------------------------------------------------------------------

def circle_iou(first, second):
    """Intersection over union of two discs given as dicts with x, y, radius."""
    r1, r2 = first["radius"], second["radius"]
    distance = math.hypot(first["x"] - second["x"], first["y"] - second["y"])
    if distance >= r1 + r2:
        intersection = 0.0
    elif distance <= abs(r1 - r2):
        intersection = math.pi * min(r1, r2) ** 2
    else:
        angle1 = math.acos((distance ** 2 + r1 ** 2 - r2 ** 2) / (2 * distance * r1))
        angle2 = math.acos((distance ** 2 + r2 ** 2 - r1 ** 2) / (2 * distance * r2))
        triangle = 0.5 * math.sqrt((-distance + r1 + r2) * (distance + r1 - r2)
                                   * (distance - r1 + r2) * (distance + r1 + r2))
        intersection = r1 ** 2 * angle1 + r2 ** 2 * angle2 - triangle
    union = math.pi * (r1 ** 2 + r2 ** 2) - intersection
    return intersection / union


def compare(detection, label):
    """Localisation errors of a detection against the label of the same ball."""
    return {
        "centre_error": math.hypot(detection["x"] - label["x"], detection["y"] - label["y"]),
        "dx": detection["x"] - label["x"],
        "dy": detection["y"] - label["y"],
        "radius_error": detection["radius"] - label["radius"],
        "iou": circle_iou(detection, label),
    }


def disc_coverage(mask_rows, label):
    """Share of the labelled disc covered by a mask: (whole disc, upper half, lower half)."""
    height, width = len(mask_rows), len(mask_rows[0])
    cx, cy, radius = label["x"], label["y"], label["radius"]
    pixels = {"upper": 0, "lower": 0}
    covered = {"upper": 0, "lower": 0}
    for y in range(max(0, cy - radius), min(height, cy + radius + 1)):
        half = "upper" if y < cy else "lower"
        for x in range(max(0, cx - radius), min(width, cx + radius + 1)):
            if (x - cx) ** 2 + (y - cy) ** 2 <= radius ** 2:
                pixels[half] += 1
                covered[half] += 1 if mask_rows[y][x] else 0
    return ((covered["upper"] + covered["lower"]) / (pixels["upper"] + pixels["lower"]),
            covered["upper"] / pixels["upper"], covered["lower"] / pixels["lower"])


# ---------------------------------------------------------------------------
# Scoring
# ---------------------------------------------------------------------------

def score_image(detections, labels):
    """Match detections and labels of one image, one colour at a time.

    The detector reports at most one ball per colour and no test photo holds
    two balls of the same colour, so the match is by colour. A detection is
    'found' when its centre lies inside the labelled ball; otherwise the ball
    counts as missed and the detection as false ('misplaced').
    """
    rows = []
    for colour in COLOURS:
        label = next((ball for ball in labels if ball["colour"] == colour), None)
        detection = next((ball for ball in detections if ball["colour"] == colour), None)
        if label is None and detection is None:
            continue
        row = {"colour": colour, "label": label, "detection": detection}
        if label is None:
            row["verdict"] = "false_detection"
        elif detection is None:
            row["verdict"] = "missed"
        else:
            row.update(compare(detection, label))
            row["verdict"] = "found" if row["centre_error"] <= label["radius"] else "misplaced"
        rows.append(row)
    return rows


def count(scored):
    """Aggregate counts over {image: rows}."""
    verdicts = [row["verdict"] for rows in scored.values() for row in rows]
    labelled = {image: [row for row in rows if row["label"]] for image, rows in scored.items()}
    empty_scenes = [image for image, rows in labelled.items() if not rows]
    return {
        "balls": sum(len(rows) for rows in labelled.values()),
        "balls_found": verdicts.count("found"),
        "balls_missed": verdicts.count("missed") + verdicts.count("misplaced"),
        "false_detections": verdicts.count("false_detection") + verdicts.count("misplaced"),
        "empty_scenes": len(empty_scenes),
        "empty_scenes_without_detection": sum(1 for image in empty_scenes if not scored[image]),
        "images": len(scored),
        "images_fully_correct": sum(1 for rows in scored.values()
                                    if all(row["verdict"] == "found" for row in rows)),
    }


def localisation(rows):
    """Summary statistics over a list of compared rows."""
    centre = [row["centre_error"] for row in rows]
    radius = [row["radius_error"] for row in rows]
    iou = [row["iou"] for row in rows]
    return {
        "balls": len(rows),
        "centre_error_median_px": round(statistics.median(centre), 1),
        "centre_error_max_px": round(max(centre), 1),
        "vertical_offset_mean_px": round(statistics.mean(row["dy"] for row in rows), 1),
        "radius_error_mean_px": round(statistics.mean(radius), 1),
        "radius_error_abs_median_px": round(statistics.median(abs(value) for value in radius), 1),
        "radius_error_abs_max_px": max(abs(value) for value in radius),
        "iou_median": round(statistics.median(iou), 2),
        "iou_min": round(min(iou), 2),
    }


# ---------------------------------------------------------------------------
# Experiments
# ---------------------------------------------------------------------------

def run_photos(binary, labels):
    """Detections, masks and scores on the unmodified photos."""
    masks, scored = {}, {}
    for name in image_names():
        detections, masks[name] = run_detector(binary, PHOTO_DIR / f"{name}.txt", WORK_DIR / "photos", masks=True)
        scored[name] = score_image(detections, labels[name])
    return masks, scored


def apply_corrections(colour, x, y, radius):
    """The integer corrections of find_clusters_attributes (cluster.c)."""
    if colour == "orange":
        y = y * (10000 - 13 * radius) // 10000
    if colour == "yellow":
        y = y * (10000 + 15 * radius) // 10000
    if colour in ("orange", "yellow"):
        radius = radius * 112 // 100
    return x, y, radius


def run_masks(scored, masks):
    """Study the mask kept for each ball found.

    Reads the largest-component mask exported by the program and computes how
    much of the labelled disc it covers, and the centre and radius of its
    bounding box before the corrections (same formulas as cluster.c). As a
    consistency check, re-applying the corrections must give the program output.
    """
    rows = []
    for image, image_rows in scored.items():
        for row in image_rows:
            if row["verdict"] != "found":
                continue
            colour, detection, label = row["colour"], row["detection"], row["label"]
            _, _, mask_rows = read_pgm(masks[image][f"{colour}_largest"])
            min_x, min_y, max_x, max_y = mask_bounding_box(mask_rows)
            box = {
                "x": min_x + (max_x - min_x) // 2,
                "y": min_y + (max_y - min_y) // 2,
                "radius": max((max_x - min_x) // 2, (max_y - min_y) // 2),
            }
            expected = apply_corrections(colour, box["x"], box["y"], box["radius"])
            if expected != (detection["x"], detection["y"], detection["radius"]):
                sys.exit(f"{image} {colour}: mask bounding box {box} does not explain the output {detection}")
            rows.append({"image": image, "colour": colour, "label": label, "box": box, "detection": detection,
                         "coverage": disc_coverage(mask_rows, label),
                         "box_errors": compare(box, label), "output_errors": compare(detection, label)})
    return rows


def scale_image(source, target, gain):
    """Write a copy of a text image with every sample multiplied by gain / 100."""
    tokens = source.read_text().split()
    table = {str(value): str(min(255, (value * gain + 50) // 100)) for value in range(256)}
    target.write_text(" ".join(tokens[:3]) + "\n" + " ".join(table[token] for token in tokens[3:]) + "\n")


def run_brightness(binary, labels):
    """Detection counts when all photos are uniformly darkened or brightened."""
    work = WORK_DIR / "brightness"
    work.mkdir(parents=True, exist_ok=True)
    sweep = []
    for gain in BRIGHTNESS_GAINS:
        scored = {}
        for name in image_names():
            scaled = work / f"{name}.txt"
            scale_image(PHOTO_DIR / f"{name}.txt", scaled, gain)
            detections, _ = run_detector(binary, scaled, work)
            scored[name] = score_image(detections, labels[name])
        found_by_colour = {
            colour: sum(1 for rows in scored.values() for row in rows
                        if row["colour"] == colour and row["verdict"] == "found")
            for colour in COLOURS
        }
        sweep.append({"gain_percent": gain, **count(scored), "found_by_colour": found_by_colour})
    return sweep


# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------

def csv_text(header, rows):
    buffer = io.StringIO()
    writer = csv.writer(buffer, lineterminator="\n")
    writer.writerow(header)
    writer.writerows(rows)
    return buffer.getvalue()


def detections_csv(scored):
    rows = []
    for image, image_rows in scored.items():
        if not image_rows:
            rows.append([image, "none", "empty_scene_no_detection"] + [""] * 9)
        for row in image_rows:
            detection, label = row["detection"], row["label"]
            rows.append([
                image, row["colour"], row["verdict"],
                *([detection["x"], detection["y"], detection["radius"]] if detection else ["", "", ""]),
                *([label["x"], label["y"], label["radius"]] if label else ["", "", ""]),
                f"{row['centre_error']:.1f}" if "centre_error" in row else "",
                row.get("radius_error", ""),
                f"{row['iou']:.2f}" if "iou" in row else "",
            ])
    return csv_text(["image", "colour", "verdict", "detected_x", "detected_y", "detected_radius",
                     "label_x", "label_y", "label_radius", "centre_error_px", "radius_error_px", "circle_iou"], rows)


def masks_csv(rows):
    return csv_text(
        ["image", "colour", "label_x", "label_y", "label_radius",
         "disc_covered", "upper_half_covered", "lower_half_covered",
         "box_x", "box_y", "box_radius", "output_x", "output_y", "output_radius",
         "box_centre_error_px", "output_centre_error_px", "box_radius_error_px", "output_radius_error_px",
         "box_iou", "output_iou"],
        [[row["image"], row["colour"],
          row["label"]["x"], row["label"]["y"], row["label"]["radius"],
          *(f"{share:.2f}" for share in row["coverage"]),
          row["box"]["x"], row["box"]["y"], row["box"]["radius"],
          row["detection"]["x"], row["detection"]["y"], row["detection"]["radius"],
          f"{row['box_errors']['centre_error']:.1f}", f"{row['output_errors']['centre_error']:.1f}",
          row["box_errors"]["radius_error"], row["output_errors"]["radius_error"],
          f"{row['box_errors']['iou']:.2f}", f"{row['output_errors']['iou']:.2f}"]
         for row in rows])


def brightness_csv(sweep):
    return csv_text(
        ["gain_percent", "balls_found", "balls_missed", "false_detections", "empty_scenes_without_detection",
         "images_fully_correct", "orange_found", "blue_found", "yellow_found"],
        [[entry["gain_percent"], entry["balls_found"], entry["balls_missed"], entry["false_detections"],
          entry["empty_scenes_without_detection"], entry["images_fully_correct"],
          *(entry["found_by_colour"][colour] for colour in COLOURS)]
         for entry in sweep])


def markdown_table(header, rows, numeric_from=1):
    lines = ["| " + " | ".join(header) + " |",
             "|" + "|".join(" --- " if index < numeric_from else " ---: " for index in range(len(header))) + "|"]
    lines += ["| " + " | ".join(str(cell) for cell in row) + " |" for row in rows]
    return "\n".join(lines)


def results_markdown(summary):
    counts = summary["detection"]
    per_colour = summary["dataset"]["balls_per_colour"]
    parts = []

    parts.append("**Detection.**\n\n" + markdown_table(
        ["On the 20 photos", "Result"],
        [["Balls found with the right colour, centre inside the labelled ball",
          f"{counts['balls_found']} / {counts['balls']}"],
         ["Balls missed", counts["balls_missed"]],
         ["False detections", counts["false_detections"]],
         ["Empty scenes with no detection", f"{counts['empty_scenes_without_detection']} / {counts['empty_scenes']}"],
         ["Images with every ball found and nothing else", f"{counts['images_fully_correct']} / {counts['images']}"]]))

    rows = []
    for key in (*COLOURS, "all"):
        stats = summary["localisation"][key]
        rows.append([key, stats["balls"], f"{stats['centre_error_median_px']:.1f}",
                     f"{stats['centre_error_max_px']:.1f}", f"{stats['radius_error_abs_median_px']:.1f}",
                     stats["radius_error_abs_max_px"], f"{stats['iou_median']:.2f}", f"{stats['iou_min']:.2f}"])
    parts.append("**Position and size.** Reported circles against the labelled circles:\n\n" + markdown_table(
        ["Colour", "Balls", "Centre error, median (px)", "Centre error, max (px)",
         "Radius error, median (px)", "Radius error, max (px)", "Circle IoU, median", "Circle IoU, min"],
        rows))

    rows = [[colour, per_colour[colour], *(f"{summary['mask_coverage'][colour][key]} %"
                                           for key in ("disc_median_percent", "upper_half_median_percent",
                                                       "lower_half_median_percent"))]
            for colour in COLOURS]
    parts.append("**What the masks catch.** Share of each labelled disc covered by the component that is kept, "
                 "median over the balls of a colour:\n\n" + markdown_table(
                     ["Colour", "Balls", "Whole disc", "Upper half", "Lower half"], rows))

    rows = []
    for colour in ("orange", "yellow"):
        for key, title in (("bounding_box", "bounding box of the mask"), ("output", "after the corrections (output)")):
            stats = summary["corrections"][colour][key]
            rows.append([colour, title, f"{stats['centre_error_median_px']:.1f}",
                         f"{stats['vertical_offset_mean_px']:+.1f}", f"{stats['radius_error_mean_px']:+.1f}",
                         f"{stats['iou_median']:.2f}"])
    parts.append("**Effect of the empirical corrections.** Orange and yellow balls, before and after "
                 "(a positive vertical offset means too low in the image):\n\n" + markdown_table(
                     ["Colour", "Estimate", "Centre error, median (px)", "Vertical offset, mean (px)",
                      "Radius error, mean (px)", "Circle IoU, median"],
                     rows, numeric_from=2))

    rows = [[f"{entry['gain_percent']} %", f"{entry['balls_found']} / {entry['balls']}",
             *(f"{entry['found_by_colour'][colour]} / {per_colour[colour]}" for colour in COLOURS),
             entry["false_detections"],
             f"{entry['images_fully_correct']} / {entry['images']}"]
            for entry in summary["brightness"]]
    parts.append("**Sensitivity to brightness.** Same photos with every RGB sample multiplied by a gain and "
                 "clipped to 255 (a simulated exposure change, not new photos):\n\n" + markdown_table(
                     ["Gain", "Balls found", "Orange", "Blue", "Yellow", "False detections", "Images fully correct"],
                     rows))

    return "\n\n".join(parts) + "\n"


def build_outputs(binary):
    labels = load_ground_truth()
    names = image_names()
    if sorted(labels) != names:
        sys.exit("ground_truth.csv and the images of IMG_300/ do not list the same names")

    masks, scored = run_photos(binary, labels)
    found = [row for rows in scored.values() for row in rows if row["verdict"] == "found"]
    mask_rows = run_masks(scored, masks)
    sweep = run_brightness(binary, labels)

    def of_colour(rows, colour):
        return [row for row in rows if row["colour"] == colour]

    def median_percent(rows, index):
        return round(100 * statistics.median(row["coverage"][index] for row in rows))

    balls_per_colour = {colour: sum(1 for balls in labels.values() for ball in balls if ball["colour"] == colour)
                        for colour in COLOURS}
    summary = {
        "criterion": "a ball is found when a detection of its colour has its centre inside the labelled circle",
        "dataset": {
            "images": len(names),
            "images_with_balls": sum(1 for balls in labels.values() if balls),
            "empty_scenes": sum(1 for balls in labels.values() if not balls),
            "balls": sum(balls_per_colour.values()),
            "balls_per_colour": balls_per_colour,
        },
        "detection": count(scored),
        "localisation": {
            **{colour: localisation(of_colour(found, colour)) for colour in COLOURS},
            "all": localisation(found),
        },
        "mask_coverage": {
            colour: {
                "disc_median_percent": median_percent(of_colour(mask_rows, colour), 0),
                "upper_half_median_percent": median_percent(of_colour(mask_rows, colour), 1),
                "lower_half_median_percent": median_percent(of_colour(mask_rows, colour), 2),
            }
            for colour in COLOURS
        },
        "corrections": {
            colour: {
                "bounding_box": localisation([row["box_errors"] for row in of_colour(mask_rows, colour)]),
                "output": localisation([row["output_errors"] for row in of_colour(mask_rows, colour)]),
            }
            for colour in ("orange", "yellow")
        },
        "brightness": sweep,
    }
    return {
        "detections.csv": detections_csv(scored),
        "masks.csv": masks_csv(mask_rows),
        "brightness.csv": brightness_csv(sweep),
        "summary.json": json.dumps(summary, indent=2) + "\n",
        "results.md": results_markdown(summary),
    }


def readme_with_results(text, block):
    start = text.find(README_START)
    end = text.find(README_END)
    if start < 0 or end < start:
        return None
    return text[:start + len(README_START)] + "\n" + block + text[end:]


def read_normalised(path):
    return path.read_text(encoding="utf-8").replace("\r\n", "\n") if path.is_file() else None


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--binary", help="path of the detector (default: PFR or PFR.exe at the repository root)")
    parser.add_argument("--check", action="store_true",
                        help="do not write anything; exit 1 if the committed results or README differ")
    args = parser.parse_args()

    outputs = build_outputs(find_binary(args.binary))
    readme = read_normalised(README)
    new_readme = readme_with_results(readme, outputs["results.md"]) if readme is not None else None

    if args.check:
        stale = [f"results/{name}" for name, text in outputs.items() if read_normalised(RESULTS_DIR / name) != text]
        if readme is not None and new_readme is None:
            stale.append("README.md (results markers not found)")
        elif readme is not None and new_readme != readme:
            stale.append("README.md (results block)")
        if stale:
            print("Out of date: " + ", ".join(stale))
            print("Run 'python scripts/evaluate.py' and commit the result.")
            return 1
        print(f"{len(outputs)} result files and the README tables match the detector output.")
        return 0

    RESULTS_DIR.mkdir(exist_ok=True)
    for name, text in outputs.items():
        (RESULTS_DIR / name).write_text(text, encoding="utf-8", newline="\n")
    if new_readme is not None and new_readme != readme:
        README.write_text(new_readme, encoding="utf-8", newline="\n")
    sys.stdout.write(outputs["results.md"])
    return 0


if __name__ == "__main__":
    sys.exit(main())
